=== yast/yast-installation/control/control.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT addon ( #PCDATA ) >

<!ELEMENT addons ( addon ) >
<!ATTLIST addons config:type NMTOKEN #FIXED "list" >

<!ELEMENT archs ( #PCDATA ) >

<!ELEMENT arguments ( #PCDATA ) >

<!ELEMENT base_selection ( #PCDATA ) >
<!ELEMENT enable_back ( #PCDATA ) >
<!ELEMENT enable_next ( #PCDATA ) >

<!ELEMENT defaults ( archs?, arguments?, enable_back?, enable_next?) >

<!ENTITY % y2_globals "language| keyboard| timezone| enable_autologin| runlevel
| use_desktop_scheduler|io_scheduler|ui_mode" >
<!ELEMENT globals (%y2_globals;)* >

<!ELEMENT keyboard ( #PCDATA ) >
<!ELEMENT runlevel ( #PCDATA ) >
<!ELEMENT ui_mode ( #PCDATA ) >

<!ELEMENT label ( #PCDATA ) >

<!ELEMENT language ( #PCDATA ) >
<!ELEMENT skip_language_dialog ( #PCDATA ) >
<!ATTLIST skip_language_dialog config:type NMTOKEN #FIXED "boolean" >

<!ELEMENT io_scheduler ( #PCDATA ) >
<!ELEMENT only_update_installed ( #PCDATA ) >
<!ATTLIST only_update_installed config:type NMTOKEN #FIXED "boolean" >
<!ELEMENT use_desktop_scheduler ( #PCDATA ) >
<!ATTLIST use_desktop_scheduler config:type NMTOKEN #FIXED "boolean" >
<!ELEMENT enable_autologin ( #PCDATA ) >
<!ATTLIST enable_autologin config:type NMTOKEN #FIXED "boolean" >

<!ELEMENT mode ( #PCDATA ) >

<!ENTITY % wf_module "archs | arguments| enable_back| enable_next | label | name | proposal | update | retranslate" >
<!ELEMENT module (%wf_module;)* >

<!ELEMENT modules ( module+ ) >
<!ATTLIST modules config:type NMTOKEN #FIXED "list" >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT package ( #PCDATA ) >

<!ELEMENT packages ( package ) >
<!ATTLIST packages config:type NMTOKEN #FIXED "list" >

<!ELEMENT productDefines ( textdomain, globals, software, partitioning, proposals, workflows ) >




<!ELEMENT proposal ( archs | enable_skip| locked_modules |  mode | name | proposal_modules | stage )* >
<!ELEMENT proposal_modules (proposal_module+)>
<!ATTLIST proposal_modules config:type NMTOKEN #FIXED "list" >
<!ELEMENT locked_modules (proposal_module+)>
<!ATTLIST locked_modules config:type NMTOKEN #FIXED "list" >

<!ELEMENT proposal_module (#PCDATA)>

<!ELEMENT proposals ( proposal+ ) >
<!ATTLIST proposals config:type NMTOKEN #FIXED "list" >

<!ELEMENT selection_type ( #PCDATA ) >
<!ATTLIST selection_type config:type NMTOKEN #FIXED "symbol" >

<!ELEMENT software (delete_old_packages| selection_type| base_selection|
        addons| packages|only_update_installed|software_proposal)* >
<!ELEMENT delete_old_packages ( #PCDATA ) >
<!ELEMENT software_proposal ( #PCDATA ) >
<!ATTLIST delete_old_packages config:type NMTOKEN #FIXED "boolean" >

<!ELEMENT stage ( #PCDATA ) >

<!ELEMENT textdomain ( #PCDATA ) >

<!ELEMENT timezone ( #PCDATA ) >

<!ELEMENT type ( #PCDATA ) >

<!ELEMENT retranslate ( #PCDATA ) >
<!ATTLIST retranslate config:type NMTOKEN #FIXED "boolean" >

<!ELEMENT update ( #PCDATA ) >
<!ATTLIST update config:type NMTOKEN #FIXED "boolean" >

<!ELEMENT workflow ( defaults? | label | mode | modules | stage )* >

<!ELEMENT workflows ( workflow+ ) >
<!ATTLIST workflows config:type NMTOKEN #FIXED "list" >

<!ELEMENT partitioning (evms_config?)>
<!ELEMENT evms_config ( #PCDATA ) >
<!ATTLIST evms_config config:type NMTOKEN #FIXED "boolean" >


<!ATTLIST productDefines
        xmlns CDATA #REQUIRED
        xmlns:config CDATA #REQUIRED
>

=== yast/yast-installation/control/control.SLES.xml
<?xml version="1.0"?>
<!DOCTYPE productDefines SYSTEM "/usr/share/YaST2/control/control.dtd">
<productDefines  xmlns="http://www.suse.com/1.0/yast2ns"
    xmlns:config="http://www.suse.com/1.0/configns">

<!--
Work around for the text domain
textdomain="control"
-->

    <textdomain>control</textdomain>
    <globals>
        <enable_autologin config:type="boolean">false</enable_autologin>
    </globals>
    <software>
        <delete_old_packages config:type="boolean">false</delete_old_packages>
        <selection_type config:type="symbol">auto</selection_type>
    </software>

    <proposals config:type="list">
        <proposal>
            <mode>installation</mode>
            <stage>initial</stage>
            <type>initial</type>

            <proposal_modules config:type="list">
                <proposal_module>hwinfo</proposal_module>
                <proposal_module>mode</proposal_module>
                <proposal_module>keyboard</proposal_module>
                <proposal_module>mouse</proposal_module>
                <proposal_module>partitions</proposal_module>
                <proposal_module>software</proposal_module>
                <proposal_module>bootloader</proposal_module>
                <proposal_module>timezone</proposal_module>
                <proposal_module>language</proposal_module>
                <proposal_module>runlevel</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <mode>installation</mode>
            <type>dirinstall</type>
            <stage>normal</stage>
            <proposal_modules config:type="list">
                <proposal_module>language</proposal_module>
                <proposal_module>dirinstall_options</proposal_module>
                <proposal_module>software</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <mode>installation</mode>
            <type>uml</type>
            <stage>normal</stage>
            <proposal_modules config:type="list">
                <proposal_module>uml_user</proposal_module>
                <proposal_module>uml_options</proposal_module>
                <proposal_module>uml_disks</proposal_module>
                <proposal_module>uml_network</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <mode>update</mode>
            <type>initial</type>
            <stage>normal</stage>
            <proposal_modules config:type="list">
                <proposal_module>mode</proposal_module>
                <proposal_module>rootpart</proposal_module>
                <proposal_module>update</proposal_module>
                <proposal_module>packages</proposal_module>
                <proposal_module>backup</proposal_module>
                <proposal_module>language</proposal_module>
                <proposal_module>keyboard</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <mode>update</mode>
            <stage>initial</stage>
            <type>initial</type>
            <proposal_modules config:type="list">
                <proposal_module>mode</proposal_module>
                <proposal_module>rootpart</proposal_module>
                <proposal_module>update</proposal_module>
                <proposal_module>packages</proposal_module>
                <proposal_module>backup</proposal_module>
                <proposal_module>language</proposal_module>
                <proposal_module>keyboard</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <archs>s390</archs>
            <mode>installation</mode>
            <stage>initial</stage>
            <type>initial</type>
            <proposal_modules config:type="list">
                <proposal_module>mode</proposal_module>
                <proposal_module>partitions</proposal_module>
                <proposal_module>software</proposal_module>
                <proposal_module>timezone</proposal_module>
                <proposal_module>language</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <archs>s390</archs>
            <mode>update</mode>
            <stage>initial</stage>
            <type>initial</type>
            <proposal_modules config:type="list">
                <proposal_module>mode</proposal_module>
                <proposal_module>rootpart</proposal_module>
                <proposal_module>update</proposal_module>
                <proposal_module>packages</proposal_module>
                <proposal_module>backup</proposal_module>
                <proposal_module>language</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <type>network</type>
            <stage>continue</stage>
            <proposal_modules config:type="list">
                <proposal_module>lan</proposal_module>
                <proposal_module>dsl</proposal_module>
                <proposal_module>isdn</proposal_module>
                <proposal_module>modem</proposal_module>
                <proposal_module>proxy</proposal_module>
                <proposal_module>remote</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <type>hardware</type>
            <stage>continue</stage>
            <proposal_modules config:type="list">
                <proposal_module>x11</proposal_module>
                <proposal_module>printer</proposal_module>
                <proposal_module>sound</proposal_module>
                <proposal_module>tv</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <archs>s390,ppc64</archs>
            <type>network</type>
            <stage>continue</stage>
            <proposal_modules config:type="list">
                <proposal_module>lan</proposal_module>
                <proposal_module>proxy</proposal_module>
                <proposal_module>remote</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <archs>ppc64</archs>
            <type>hardware</type>
            <stage>continue</stage>
            <proposal_modules config:type="list">
                <proposal_module>x11</proposal_module>
                <proposal_module>printer</proposal_module>
            </proposal_modules>
        </proposal>
        <proposal>
            <archs>s390</archs>
            <type>hardware</type>
            <stage>continue</stage>
            <proposal_modules config:type="list">
                <proposal_module>printer</proposal_module>
            </proposal_modules>
        </proposal>
    </proposals>

    <workflows config:type="list">
        <workflow>
            <defaults>
                <arguments>false,false</arguments>
                <archs>all</archs>
            </defaults>
            <stage>initial</stage>
	    <label>Base Installation</label>
            <mode>installation</mode>
            <modules  config:type="list">
                <module>
                    <name>info</name>
                    <arguments>false,true</arguments>
                </module>
                <module>
                    <name>language</name>
                    <arguments>false,true,true</arguments>
	            <label>Language</label>
                </module>
                <module>
                    <name>proposal</name>
                    <arguments>true,true,`ini</arguments>
	            <label>Installaton Settings</label>
                </module>
                <module>
                    <name>do_resize</name>
                    <update config:type="boolean">false</update>
                    <archs>i386,x86_64,ia64</archs>
	            <label>Perform Installation</label>
                </module>
                <module>
                    <name>prepdisk</name>
	            <label>Perform Installation</label>
                </module>
                <module>
                    <name>kickoff</name>
	            <label>Perform Installation</label>
                </module>
                <module>
                    <name>rpmcopy</name>
	            <label>Perform Installation</label>
                </module>
                <module>
                    <name>finish</name>
	            <label>Perform Installation</label>
                </module>
            </modules>
        </workflow>
        <workflow>
            <defaults>
                <arguments>false,false</arguments>
                <archs>all</archs>
            </defaults>
            <stage>initial</stage>
	    <label>Preparation</label>
            <mode>repair</mode>
            <modules  config:type="list">
                <module>
	            <label>System Information</label>
                    <name>info</name>
                    <arguments>false,true</arguments>
                </module>
                <module>
	            <label>Perform Repair</label>
                    <name>repair</name>
                    <arguments>false,true,true</arguments>
                </module>
            </modules>
        </workflow>
        <workflow>
            <defaults>
                <arguments>false,false</arguments>
                <archs>all</archs>
            </defaults>
            <stage>initial</stage>
	    <label>Base Installation</label>
            <mode>screen_shot</mode>
            <modules  config:type="list">
                <module>
 	            <label>Language</label>
                    <name>language</name>
                    <arguments>false,true,true</arguments>
                </module>
                <module>
	            <label>Installaton Settings</label>
                    <name>proposal</name>
                    <arguments>true,true,`ini</arguments>
                </module>
                <module>
	            <label>Perform Installation</label>
